#!/usr/bin/env bash

action=$(echo $1 | cut -f1 -d' ')
file=$(echo $1 | cut -f2 -d' ')
destFile=$(echo $file | awk '{str=$1;sub(/^src/, "dist", str); print str}')
mapFile=$(echo $destFile | awk '{str=$1; sub(/\.js$/, ".js.map", str); print str}')

if [[ $action == "unlink" ]]; then
  rm -f $destFile $mapFile
  echo "removed "$destFile
  echo "removed "$mapFile
fi

if [[ $action == "unlinkDir" ]]; then
  rm $destFile -rf
  echo "removed "$destFile
fi
